// 71-react-frontend/src/CourseInfo.tsx
import { CourseImage } from "./CourseImage";
import { Course } from "./types";

interface CourseInfoProps {
  course: Course;
}

export const CourseInfo = ({ course }: CourseInfoProps) => {
  return (
    <div className="course-card js-filtered-item" data-category={course.category}>
      <CourseImage image={course.image} title={course.title} />
      <div className="course-card__info">
        <h6 className="course-card__title">
          <a
            href={course.link}
            rel="noreferrer"
            target="_blank"
          >
            {course.title}
          </a>
        </h6>
        <strong>{course.teachers}</strong>
        <p>
          {course.description}
        </p>
      </div>
    </div >
  );
};

// 73-vue-frontend/src/components/CourseInfo.vue
<template>
  <div class="course-card">
    <CourseImage :image="course.image" :title="course.title" />
    <div class="course-card__info">
      <h6 class="course-card__title">
        <a :href="course.link" rel="noreferrer" target="_blank">
          {{ course.title }}
        </a>
      </h6>
      <strong>{{ course.teachers }}</strong>
      <p>
        {{ description }}
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import { Course } from "@/types";
import CourseImage from "@/components/CourseImage.vue";

export default defineComponent({
  name: "App",
  components: {
    CourseImage,
  },
  props: {
    course: {
      type: Object as PropType<Course>,
      required: true,
    },
  },
  computed: {
    description(): string {
      return this.course.description.length > 70
        ? this.course.description.substr(0, 70) + "…"
        : this.course.description;
    },
  },
});
</script>
