// 73-vue-frontend/src/App.vue
<template>
  <div class="App">
    <header class="App-header">
      <h1>Courses</h1>
    </header>
    <div id="courses" class="courses-grid">
      <CourseInfo
        v-for="course in courses"
        :key="course.title"
        :course="course"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { useCourses } from "@/useCourses";
import CourseInfo from "@/components/CourseInfo.vue";

export default defineComponent({
  name: "App",
  components: {
    CourseInfo,
  },
  setup() {
    return useCourses();
  },
});
</script>

// 71-react-frontend/src/App.tsx
import React from 'react';
import './styles/App.css';
import { useCourses } from './useCourses';
import { CourseInfo } from './CourseInfo';

function App() {
  const { courses } = useCourses();

  return (
    <div className="App">
      <header className="App-header">
        <h1>Courses</h1>
      </header>
      <div id="courses" className="courses-grid">
        {courses.map(course => (
          <CourseInfo key={course.title} course={course} />
        ))}
      </div>
    </div>
  );
}

export default App;
