// 73-vue-frontend/src/components/CourseImage.vue
<template>
  <img class="course-card__img" :alt="title" :src="`img/cursos/${image}`" />
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    title: {
      type: String,
      required: true,
    },
    image: {
      type: String,
      required: true,
    },
  },
});
</script>

// 61-react-frontend/src/CourseImage.tsx
import { Component } from "react";

interface CourseImageProps {
  image: string;
  title: string;
}

export class CourseImage extends Component<CourseImageProps> {
  render() {
    return (
      < img
        className="course-card__img"
        alt={this.props.title}
        src={`img/cursos/${this.props.image}`}
      />
    )
  }
}
